const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ts = require('typescript');
const root = path.resolve(__dirname, '..');
const doc = fs.readFileSync(path.join(root, 'CODEX_WALKTHROUGH.md'), 'utf8');
const blocks = [...doc.matchAll(/```ts\r?\n([\s\S]*?)```/g)].map(x => x[1]);
assert.equal(blocks.length, 4);
const source = blocks.join('\n').replace(/^import type .*;\r?\n/gm, '');
const filename = path.join(__dirname, 'plan-reference.ts');
fs.writeFileSync(filename, source);
const options = {strict:true, target:ts.ScriptTarget.ES2022, module:ts.ModuleKind.CommonJS, skipLibCheck:true, noEmit:true, types:[]};
const program = ts.createProgram([filename], options);
const errors = ts.getPreEmitDiagnostics(program);
assert.equal(errors.length, 0, errors.map(d=>ts.flattenDiagnosticMessageText(d.messageText,'\n')).join('\n'));
const js = ts.transpileModule(source, {compilerOptions:options}).outputText;
const sandbox = {exports:{}};
vm.runInNewContext(js, sandbox);
const {evaluate, summarize, day} = sandbox.exports;
const c = {entityId:'kv', modelId:'m1', eventDate:'2026-09-01', assessedAt:'2026-09-10'};
const r = {id:'R1',version:'1',basis:'internal',eventBasis:'delivery',publication:'released',validFrom:'2026-01-01',conditionIds:['C1'],citations:[{documentId:'internal-fixture',versionId:'1',locator:'1',sourceHash:'fixture',verified:true}]};
const s = {status:'applies',reason:'Synthetic test scope',evidenceIds:['scope']};
const f = {conditionId:'C1',entityId:'kv',modelId:'m1',value:true,evidenceIds:['E1'],verification:'verified',validFrom:'2026-01-01',checkedAt:'2026-09-10'};
const results=[];
function check(name, actual, expected){assert.equal(actual,expected,name);results.push({name,actual,expected});}
const e=(rule=r,ctx=c,scope=s,facts=[f])=>evaluate(rule,ctx,scope,facts).verdict;
check('pass',e(),'pass');
check('false evidence',e(r,c,s,[{...f,value:false}]),'fail');
check('missing',e(r,c,s,[]),'insufficient');
check('OCR unverified',e(r,c,s,[{...f,verification:'unverified'}]),'insufficient');
check('wrong model',e(r,c,s,[{...f,modelId:'other'}]),'insufficient');
check('wrong entity',e(r,c,s,[{...f,entityId:'other'}]),'insufficient');
check('stale',e(r,c,s,[{...f,checkedAt:'2026-08-01',maxAgeDays:7}]),'insufficient');
check('expired',e(r,c,s,[{...f,validUntilExclusive:'2026-09-01'}]),'insufficient');
check('draft',e({...r,publication:'draft'}),'review');
check('no citation',e({...r,citations:[]}),'review');
check('unknown scope',e(r,c,{...s,status:'unknown'}),'insufficient');
check('unproven exemption',e(r,c,{...s,status:'does_not_apply',evidenceIds:[]}),'insufficient');
check('exemption',e(r,c,{...s,status:'does_not_apply'}),'not_applicable');
check('outside interval',e({...r,validUntilExclusive:'2026-09-01'}),'not_applicable');
check('future event',e(r,{...c,eventDate:'2026-10-01'}),'review');
check('future check',e(r,c,s,[{...f,checkedAt:'2026-10-01'}]),'review');
check('conflict',e(r,c,s,[{...f,verification:'conflict'}]),'review');
check('duplicate fact',e(r,c,s,[f,f]),'review');
check('empty conditions',e({...r,conditionIds:[]}),'review');
check('invalid interval',e({...r,validUntilExclusive:'2025-01-01'}),'review');
check('invalid day',day('2026-02-30'),null);
check('leap day',day('2024-02-29')!==null,true);
const pass=evaluate(r,c,s,[f]);
check('empty required',summarize([],[]),'insufficient');
check('missing required',summarize(['R1','R2'],[pass]),'insufficient');
check('all NA',summarize(['R1'],[{...pass,verdict:'not_applicable'}]),'insufficient');
check('cannot average fail',summarize(['R1'],[{...pass,verdict:'fail'}]),'fail');
check('duplicate finding',summarize(['R1'],[pass,pass]),'review');
check('complete',summarize(['R1'],[pass]),'pass');
const groups = new Set([...doc.matchAll(/^\| (MD\d{2}) \|/gm)].map(x=>x[1]));
const templates = new Set([...doc.matchAll(/^\| (T\d{2}) \|/gm)].map(x=>x[1]));
assert.equal(groups.size,40);assert.equal(templates.size,14);
const report={testedAt:new Date().toISOString(),scope:'Plan code snippets: strict TypeScript and synthetic logic only; no live website or legal validation',typecheckErrors:errors.length,passed:results.length,groups:groups.size,templates:templates.size,results};
fs.writeFileSync(path.join(__dirname,'plan-verification.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify({typecheckErrors:0,passed:results.length,groups:groups.size,templates:templates.size}));
