version: '3.8'  
services:  
  medical-backend:  
    build: .  
    container_name: medical-backend  
    restart: unless-stopped  
    ports:  
      - 4000:4000  
    volumes:  
      - ./database.sqlite:/app/database.sqlite  
      - ./uploads:/app/uploads  
    env_file:  
      - .env 
