import { Button } from '@/components/ui/button';
export function AuditHandoffGuide({openWork,openLaws}:{openWork:()=>void;openLaws:()=>void}){
  const stages=[
    {title:'1. Tiếp nhận và xác định phạm vi',rows:['Lưu quyết định/thông báo nhận được, ngày nhận thực tế, pháp nhân, kỳ, nội dung, đoàn và đầu mối liên hệ. Không suy kỳ kiểm tra từ tháng đoàn vào.','Đối chiếu căn cứ thủ tục và quy định chuyển tiếp tại thời điểm kiểm tra. Nếu có điểm chưa rõ về thẩm quyền, phạm vi hoặc thời hạn, lập yêu cầu làm rõ bằng văn bản và lưu phản hồi.','Phân công kế toán trưởng điều phối; từng mảng có người chuẩn bị sổ và người xác nhận nghiệp vụ. Hạn nội bộ là ngày công ty tự đặt, không gọi là hạn pháp luật.'],output:'Một hồ sơ quyết định + bảng phạm vi + danh sách người phụ trách; chưa đủ thông tin ghi rõ chưa xác định.'},
    {title:'2. Ghi từng yêu cầu của đoàn thành công việc',rows:['Chép đúng nội dung, người/cơ quan yêu cầu, ngày nhận và hạn được thông báo. Tách yêu cầu quá rộng thành từng nội dung có thể trả lời và kiểm chứng.','Xác định nguồn lấy số: sổ cái, sổ chi tiết, tờ khai, hợp đồng, hóa đơn, sao kê hay hồ sơ sản xuất. Ghi tên file và kỳ/phiên bản, tránh mỗi lần xuất phần mềm ra số khác nhau.','Nếu cần gia hạn hoặc chưa có tài liệu, ghi lý do thật và nội dung cần đề nghị; không tự đánh dấu đã được gia hạn.'],output:'Mỗi yêu cầu có người, hạn thực tế, nguồn số liệu và việc còn thiếu.'},
    {title:'3. Rà chênh lệch trước khi lập giải trình',rows:['Nhóm đã đủ căn cứ: ghi dữ kiện, phép đối chiếu và điều khoản đã đọc đúng kỳ. Nhóm thiếu hồ sơ: chỉ rõ thiếu file gì, ai bổ sung. Nhóm có sai sót: định lượng, xác định kỳ và đề xuất xử lý để người có thẩm quyền rà.','Không mặc cả tỷ lệ xuất toán “50/50”. Mỗi khoản phải xét trên chứng cứ, bản chất nghiệp vụ và căn cứ pháp luật; không nhượng bộ một khoản để đổi lấy khoản khác.','Không lập lùi ngày, ghi hộ chữ ký, bịa nghiệm thu hoặc khẳng định toàn bộ chi phí đúng khi chưa kiểm. Giải trình phải thể hiện cả nội dung chưa đủ căn cứ.'],output:'Bảng chênh lệch có chứng từ, đề xuất xử lý và người rà; kết quả tính khớp không thay kết luận thuế.'},
    {title:'4. Lưu bản bàn giao và theo dõi bản gốc',rows:['Chọn các chứng từ đã được người rà xác nhận trong cùng đợt. Điền bản giải trình thực tế rồi chuyển trạng thái “Đã bàn giao”; app giữ phiên bản nội dung và danh mục file tại thời điểm đó.','Khi thực tế gửi/nhận tài liệu, lưu biên nhận với người nhận, ngày, danh mục, số bản, bản gốc/bản sao và điều kiện hoàn trả nếu có. Trạng thái trong app là sổ theo dõi nội bộ, không phải đã gửi hồ sơ cho cơ quan thuế.','Nếu thay nội dung, giữ bản cũ, lập bản chỉnh sửa và ghi lý do. Bản gốc giao ra ngoài cần được theo dõi đến lúc nhận lại.'],output:'Bản giải trình + danh mục tài liệu + phiên bản bàn giao + vị trí biên nhận.'},
    {title:'5. Rà biên bản và theo dõi kết quả',rows:['Đọc từng nội dung, kỳ, số tiền, căn cứ và tài liệu đã nộp trong biên bản. So lại với bảng đối chiếu của công ty; không chỉ kiểm tổng số cuối.','Nội dung chưa đồng ý: ghi rõ vấn đề, số tiền theo số liệu đã kiểm, căn cứ và chứng cứ; lưu ý kiến cùng tài liệu gửi kèm. Thời hạn và thủ tục giải trình/khiếu nại phải xác định theo văn bản áp dụng, không lấy hạn mặc định của app.','Chỉ đóng việc khi lưu được biên nhận/kết quả tương ứng. Các nghĩa vụ thực hiện sau kết luận, tài liệu cần bổ sung và việc nhận lại bản gốc tiếp tục theo dõi riêng.'],output:'Danh sách nội dung đồng ý/chưa đồng ý, hồ sơ phản hồi và công việc sau kiểm tra.'}
  ];
  return <section className="space-y-4"><header className="border rounded-xl bg-card p-5 space-y-3"><h2 className="font-bold text-xl">Làm việc với đoàn: từ yêu cầu đến kết quả</h2><p className="text-sm leading-6">Quy trình quản lý hồ sơ nội bộ. Quyền, thẩm quyền và thời hạn cụ thể phải kiểm theo quyết định và pháp luật áp dụng; không mặc định dùng thủ tục của năm cũ.</p><div className="flex flex-wrap gap-2"><Button onClick={openWork}>Mở nhật ký yêu cầu và bàn giao</Button><Button variant="outline" onClick={openLaws}>Kiểm căn cứ thủ tục trong kho luật</Button></div></header>{stages.map(s=><article key={s.title} className="border rounded-xl bg-card p-5"><h3 className="font-bold text-lg mb-3">{s.title}</h3><ul className="list-disc pl-5 space-y-3 text-sm leading-6">{s.rows.map(r=><li key={r}>{r}</li>)}</ul><p className="mt-4 rounded-lg bg-muted p-3 text-sm leading-6"><strong>Đầu ra phải lưu:</strong> {s.output}</p></article>)}</section>;
}
