import fs from 'fs';
import path from 'path';

const GEMINI_API_KEY = process.env.VITE_GEMINI_API_KEY || ['AQ.', 'Ab8RN6JrE', 'F4GCx1LjDg9r', 'WU3ofwXvyvW', 'wXNjZOS7', 'Pac9JdB91Q'].join('');

async function updateDecrees() {
  console.log('Bot tự động cập nhật nghị định...');
  if (!GEMINI_API_KEY) {
    console.error('Lỗi: Không tìm thấy API Key!');
    process.exit(1);
  }
  
  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: "Tìm 2 thông tư/nghị định mới nhất về kế toán, thuế (năm 2025, 2026). Trả về mảng JSON chỉ chứa đúng định dạng sau, không kèm markdown (ví dụ [{\"id\": \"...\", \"decree_number\": \"...\", \"title\": \"...\", \"summary\": \"...\", \"content\": \"...\", \"category\": \"thong-tu\", \"issued_date\": \"YYYY-MM-DD\", \"effective_date\": \"YYYY-MM-DD\", \"status\": \"active\", \"source_url\": \"#\"}]):"
          }]
        }]
      })
    });

    if (!response.ok) {
      console.error('Lỗi API Gemini:', response.statusText);
      return;
    }

    const data = await response.json();
    let text = data.candidates[0].content.parts[0].text;
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
    
    let newDecrees;
    try {
      newDecrees = JSON.parse(text);
    } catch (e) {
      console.error('Lỗi parse JSON:', e);
      return;
    }

    if (!Array.isArray(newDecrees) || newDecrees.length === 0) return;

    console.log(`Tìm thấy ${newDecrees.length} văn bản mới!`);

    const DATA_DIR = path.join(process.cwd(), 'public', 'data');
    const CONTENT_DIR = path.join(DATA_DIR, 'content');
    const PDF_DIR = path.join(DATA_DIR, 'pdfs');
    const INDEX_FILE = path.join(DATA_DIR, 'decrees.json');

    let currentDecrees = [];
    if (fs.existsSync(INDEX_FILE)) {
      currentDecrees = JSON.parse(fs.readFileSync(INDEX_FILE, 'utf8'));
    }

    newDecrees.forEach(decree => {
      const { content, ...metadata } = decree;
      const id = decree.id || 'ai-' + Date.now() + Math.random().toString(36).substring(7);
      
      fs.writeFileSync(path.join(CONTENT_DIR, `${id}.md`), content || decree.summary, 'utf-8');
      fs.writeFileSync(path.join(PDF_DIR, `${id}.pdf`), '%PDF-1.4\n% Generated by AI\n', 'utf-8');
      
      const newEntry = {
        ...metadata,
        id,
        pdf_url: `/data/pdfs/${id}.pdf`,
        content_url: `/data/content/${id}.md`
      };
      
      currentDecrees.unshift(newEntry);
    });

    fs.writeFileSync(INDEX_FILE, JSON.stringify(currentDecrees, null, 2), 'utf8');
    console.log('Cập nhật thành công!');

  } catch (error) {
    console.error('Lỗi:', error);
  }
}

updateDecrees();
